# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yml

build:
  os: "ubuntu-24.04"
  apt_packages:
    - libgl1
    - mesa-utils
    - xvfb
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_build:
        - sudo apt-get install -y libgl1 mesa-utils xvfb
  # -------------------------------------------------------------------
  # To uncomment when needed (typically when more than 50 commits)
  # -------------------------------------------------------------------
  #     - git fetch origin --unshallow
  #     - git rev-list --count HEAD

python:
  install:
    - method: pip
      path: .

      build:
  apt_packages:
    - libclang
    - cmake
