name: plaid-ops
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
##### RUN #####
  - hdf5
  - vtk>=9.4
  - pycgns-core
  - muscat-core=2.5
  - pip
  - pip:
##### RUN #####
    # - pyplaid==0.1.8
    - "pyplaid @ git+https://github.com/PLAID-lib/plaid.git@globals"
##### DEV #####
#---# testing
    - pytest
    - pytest-cov
#---# code formatters
    - ruff
    - pyright[nodejs]
#---# dev
    - pre-commit
#---# doc
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - myst-parser
    - jupytext
    - furo
    - pyvista[jupyter]
