name: plaid-ops
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
##### RUN #####
  - muscat=2.5.0
  - pip
  - pip:
##### RUN #####
    - git+https://github.com/PLAID-lib/plaid.git
##### DEV #####
#---# testing
    - pytest
    - pytest-cov
#---# code formatters
    - ruff
    - pyright[nodejs]
#---# dev
    - pre-commit
#---# doc
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - myst-parser
    - nbconvert
    - furo
