name: plaid-ops
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
##### RUN #####
  - hdf5
  - muscat-core=2.5
  - pip
  - pip:
##### RUN #####
    - vtk>=9.4
    - git+https://github.com/PLAID-lib/plaid.git
##### DEV #####
#---# testing
    - pytest
    - pytest-cov
#---# code formatters
    - ruff
    - pyright[nodejs]
#---# dev
    - pre-commit
#---# doc
    - sphinx
    - sphinx-autoapi
    - myst-nb
    - myst-parser
    - jupytext
    - furo
    - pyvista[jupyter]
