name: Publish to PyPI

on:
  push:
    branches:
      - '**'
  release:
    types: [created]

jobs:
  build:
    name: Build wheels
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0   # fetch full history and all tags

      - name: Install HDF5 dev libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Check version consistency
        if: github.event_name == 'release'
        run: |
          pip install .
          RELEASE_VER=${GITHUB_REF#refs/*/}
          PACKAGE_VER="$(python -c 'import plaid_ops; print(plaid_ops.__version__)')"
          if [ "$RELEASE_VER" != "$PACKAGE_VER" ]; then
            echo "Package version ($PACKAGE_VER) doesn't match tag ($RELEASE_VER)"
            exit 1
          fi

      - name: Build package
        run: |
          python -m build --wheel --outdir dist/

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-3.11
          path: dist/*.whl

  publish:
    name: Publish to PyPI
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist